### ISSUE TITLE
celfie throws when <num_samples>=2 

### ISSUE THREAD

**Issue by imdanique** [christacaggiano/celfie#7]
Hi,

When I usu one sample, celfie runs well:

```bash
python celfie.py celfie_samples_combined_ref.txt dir 1
```
But when I try the same with two samples, it fails:

```bash
python celfie.py celfie_samples_combined_ref.txt dir 2
```

Here is the error message:
```bash
Traceback (most recent call last):
  File "celfie.py", line 373, in <module>
    alpha, gamma, ll = em(
  File "celfie.py", line 182, in em
    a, g = maximization(p0, p1, x, x_depths, y, y_depths)
  File "celfie.py", line 131, in maximization
    new_alpha[n, :] = np.dot(p1[:, :, n], x[n, :]) + np.matmul(
  File "<__array_function__ internals>", line 200, in dot
TypeError: can't multiply sequence by non-int of type 'float'
```

Input is in correct format. Do you have any idea what could go wrong here? Thanks

**Comment by imdanique** [comment]
Turns out that there were missing values with "." in couple rows, I substituted them to "0" and it worked
